### PR TITLE
Fix and clean up type hints

### PR DESCRIPTION
**Pull request by gws**
Hi,

Really appreciate the work you've done on this library, it's been useful to me!

I noticed the other day when I was running the Clojure linting tool [`lein-eastwood`](https://github.com/jonase/eastwood), that the actual return type hint when calling `clj-uuid/as-uuid` was the class `UUID`, but it was not fully qualified. Because I did not have the class imported in my ns, this caused an error as the fully qualified class `UUID` did not exist.

A REPL session exhibiting the problem would look something like this:

```clojure
user=> (require 'clj-uuid)
nil
user=> (.getMostSignificantBits (clj-uuid/as-uuid "af5e967e-7820-4289-a896-34edeb08d42b"))
CompilerException java.lang.IllegalArgumentException: Unable to resolve classname: UUID, compiling:(/tmp/form-init689173904945310969.clj:1:1)
```

For more information on why this occurs, I found the [:wrong-tag](https://github.com/jonase/eastwood/blob/master/README.md#wrong-tag) section of `lein-eastwood`'s README to be very interesting and led to a number of fixes in my own code.

I fixed a number of other issues such as moving primitive return type hints out of protocols (they will cause the Clojure compiler to barf if put in the "correct" place). I left the (fully qualified) Java class return type hints on the protocols, though I'm not sure if that's idiomatic.

For consistency with all of the above, I also moved return type hints to the position just before the argument vector, which is how it is described in the [Clojure documentation](http://clojure.org/java_interop#Java%20Interop-Type%20Hints) (but not strictly necessary in all cases, see the [`lein-eastwood` README](https://github.com/jonase/eastwood/blob/master/README.md#wrong-tag) for more information).

I also included a commit where I refactor the manual setting of `*warn-on-reflection*` out into the Leiningen project map. I fixed one instance where this change caught a reflection warning.

I tried to break up the changes into discrete commits for easier review.

Thanks again, and I look forward to your feedback!

### CODE REVIEW

**Comment by danlentz** [comment]
Thanks for the fix and for pointing me to lein-eastwood.  That went ahead and made my day.  Looking at the changes now.

**Comment by danlentz** [comment]
@gws 
Ok, but on v3 and v5, from the eastwood docs:

>   "For Java classes, it is correct to use type tags on Vars like in these examples:
>     ;; Correct Java class type hints on Vars
>     (defn ^Boolean positive? [x] (> x 0))

So those should remain as they were, would you agree?  Thanks again for pointing this out and for directing me to lein-eastwood.

**Comment by gws** [comment]
@danlentz 

Yeah, I only moved them to just before the argument vector for consistency within the code and so that it matched the way return type hints are explained in the Clojure documentation. My reading of that section is they're using *correct* to differentiate from the *incorrect* usage of **primitive** type hints on the var as outlined at the start of their explanation.

Eastwood docs:

```clojure
;; no warning for this since it is fully qualified
(defn linklist3 ^java.util.LinkedList [coll] (java.util.LinkedList. coll))
```

All that said, I'm happy to make the changes to put these instances back to the way they were.

**Comment by danlentz** [comment]
@gws no need, I merged your changes.  This has also been very edifying -- much appreciated.

**Comment by gws** [comment]
@danlentz :+1: FWIW, I think some of this behavior is more a "wart" in Clojure than anything else, but there are JIRA tickets open and so hopefully some of this behavior gets easier to grok in the future.

**Pull request merged**
